### ISSUE TITLE
DevKit build error at "Build - Build.sln"

### ISSUE THREAD

**Issue by BL9** [CosmosOS/Cosmos#1076]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Installing the DevKit

#### Expected Behaviour - What do you think that should happen?
It should install without any errors.

#### Actual Behaviour - What unexpectedly happens?
It gives an error.
> System.Exception: The process failed to execute!

Full Log: 
[Installation Log.txt](https://github.com/CosmosOS/Cosmos/files/2534762/Installation.Log.txt)
Build - Build.sln Log Part:
[Build - Build.sln Seperated.txt](https://github.com/CosmosOS/Cosmos/files/2534765/Build.-.Build.sln.Seperated.txt)

#### Reproduction - How did you get this error to appear?
Trying to install it.

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
DevKit (2018-10-31)

At first sight I think it's the same problem as here [link](https://github.com/CosmosOS/Cosmos/issues/1071), but I'm not completely sure.

**Comment by zarlo** [comment]
D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(3049,5): error MSB3821: Couldn't process file ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx due to its being in the Internet or Restricted zone or having the mark of the web on the file. Remove the mark of the web if you want to process these files. [D:\Users\leten\Downloads\Cosmos\2018-10-31\Cosmos\source\Cosmos.VS.ProjectSystem\Cosmos.VS.ProjectSystem.csproj]

ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx  is most likely locked

**Comment by BL9** [comment]
Ok, tanx zarlo! This worked but now I have a problem a bit further in the installation at "Create Setup".
> Error on line 102 in D:\Users\leten\Downloads\Cosmos\2018-10-31\Cosmos\setup\Cosmos.iss: No files found matching "D:\Users\leten\Downloads\Cosmos\2018-10-31\Cosmos\.\..\Common\source\Cosmos.Core.DebugStub\*.xs"
Compile aborted.

I've taken a look, but I can't even find the directory

**Comment by sjmulder** [comment]
> No files found matching [...]..\Common\[...]

I'm guessing you need to check out https://github.com/CosmosOS/Common (next to the Cosmos and IL2CPU directories).

**Comment by BL9** [comment]
Ok, I downloaded the latest DevKit (2018-11-1) today and installed it and now it works like a charm.
