### ISSUE TITLE
Unboxing of Nullable<T> is not implemented

### ISSUE THREAD

**Issue by fanoI** [CosmosOS/Cosmos#1083]
#### Area of Cosmos - What area of Cosmos are we dealing with?
BCL tests

#### Expected Behaviour - What do you think that should happen?
The unboxing should succeed and HasValue should be true.

#### Actual Behaviour - What unexpectedly happens?
We know it is not implemented so this is totally expected but...

> 09:40:33.367007         Error: Error: Exception: System.Exception: Error compiling method 'SystemVoidBoxingTestsKernelTestUnboxingNullable': System.NotImplementedException: The method or operation is not implemented.
09:40:33.405042         Error:    at Cosmos.IL2CPU.X86.IL.Unbox.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Unbox.cs:line 78
09:40:33.405973         Error:    at Cosmos.IL2CPU.X86.IL.Unbox_Any.Execute(_MethodInfo aMethod, ILOpCode aOpCode) in C:\Users\fano\Documents\GitHub\Cosmos\IL2CPU\source\Cosmos.IL2CPU\IL\Unbox_Any.cs:line 22

#### Reproduction - How did you get this error to appear?

```cs
        private void TestUnboxingNullable()
        {
            object x = 42;

            int? y = (int?)x;

            Assert.IsTrue(y.HasValue == true, "Unboxing of Nullable<int> does not work");
        }
```

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Last devKit

**Comment by wessupermare** [comment]
Looks like this is for all generic-typed structs, not just Nullable<T> (thanks to @mterwoord for the catch).

**Comment by jp2masa** [comment]
I think this is just for `Nullable<T>`, it's a special type which should be boxed and unboxed in a specific way, according to ECMA 335.
More info: https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.IL2CPU/IL/Unbox.cs#L64 (or take a look at the `unbox` opcode description in ECMA 335).

**Comment by wessupermare** [comment]
I agree that that appears to be the specification. My concern is that we aren't treating them differently in box (https://github.com/CosmosOS/IL2CPU/blob/master/source/Cosmos.IL2CPU/IL/Box.cs) and so it will probably need to be unboxed the same as well.

**Comment by jp2masa** [comment]
Sure, the idea is to implement it in both.

**Comment by PlatinumLyfe** [comment]
For nullable, it's easy...
Just box/unbox to Object
```
int? p = null;
object z = (object)p;
Console.WriteLine(z == null); //Output: true

int? t = 32;
object y = (object)t;
Console.WriteLine(t == null); //Ouput: false
```

Is that good enough, or do you want some more info?

More info below, which is what I had started writing up for you...

But... I mean, if you're going to write something proper - don't just write it for Nullable<T> you will need to go the full way right?

So back to basics.

Remember: **struct is a ValueType**, classes are a ReferenceType.
Nullable<T> being a struct type itself cannot be null and **must** hold some value
```
int x = null; // Cannot convert null to 'int' because it is a non-nullable value type
```

With Nullable<T> you can't actually declare it as null if you initialize it using the full write-out (i.e. without using ```int?```)
Try this:
```
Nullable<int> x = new Nullable<int>(null); // ERROR: Argument 1: cannot convert from '<null>' to 'int'
```

Try this:
```
Nullable<int> x = new Nullable<int>();
Console.Writeline("{0} - {1}", x.HasValue, x.GetValueOrDefault());
Console.Writeline("{0}", x.Value);
// Outputs:
// False - 0
// Run-time exception (line 9): Nullable object must have a value.
```
x (as the ValueType) itself is not, cannot ever be null.
That is why they have explicitly made it impossible to cast  Nullable<T> to T.
They achieve the illusion of null by using a bunch of Comparers and so forth, which simply check if hasValue == false.

Go look at the reference source for Nullable<T>, it should assist with this:
https://referencesource.microsoft.com/#mscorlib/system/nullable.cs,c9505a785f9fd8c5

```GetValueOrDefault()``` with no args always just returns whatever is in the ```Nullable<T>.value``` (private) field, so if ```Nullable<T>.HasValue == false``` it is the same as ```return default(T);``` which is the same as ```return new T();```

Your problem is going to be something like this:
```
public struct Omg
{
}
public static void Main()
{
   Omg y = new Omg();
   Console.WriteLine("{0}", y);
}
// Output: Omg
```
But what exactly is the **value** of an instanced Omg? 
Its a ValueType and must have a Value (it will not be pointing to the reference)...
So we can use reflection to check for these things:
```
typeof(Omg).IsValueType // true
typeof(Nullable<int>).IsValueType // true
```
So that's your way of checking for Structs (and ValueTypes).

However you want to somehow manage them into being Nullable/null, right?

If you dig around a bit using reflection you'll find:
```typeof(Omg).BaseType == System.ValueType```
```typeof(Nullable<int>).BaseType == System.ValueType```

System.ValueType is an abstract class...
Classes are a ReferenceType...
From my (probably faulty) memory when a ReferenceType is null, it is saying the reference is a pointer to IntPtr.Zero

So then you go look at the reference source for System.ValueType:
https://referencesource.microsoft.com/#mscorlib/system/valuetype.cs,915ba3e46633f948

And this is where I lost my concentration due to the 40+ deg C temperature and my air con breaking down. 👍

**Comment by PlatinumLyfe** [comment]
Sorry I don't think I necessarily answered the difficulty (the heat clogging my brain up)...
This further comment won't help, I'm just raising some difficulties you may encounter although I'm just looking with the code out of context, no idea what you are/aren't actually boxing/unboxing.

When your in your Box.cs, if you want to check for Generic Structs I think the better check on line 29 is:
```
(xType.IsGenericType && xType.IsValueType) 
```
As was pointed out, this issue affects all Generic Struct Types.

But... How do you intend to handle a KeyValuePair<TKey, TValue> ?

It's a generic struct (ValueType) with 2 Generic Type Arguments...
So in your Unbox.cs you only refer to the first GenericTypeArguments on line 33, which for a KeyValuePair should probably be the Value (as opposed to the Key), if you're going to do any operations on it.

However with KeyValuePair<TKey, TValue> neither TKey or TValue are forced to be ValueTypes, so either could be null.

I suppose look at the mscorlib Binary serializer because structs tend to have the [Serializable] flag.

https://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/formatters/binary/binaryconverter.cs,aae60dde5afb33cb
```
// Routines to convert between the runtime type and the type as it appears on the wire
```
Which is effectively what you are trying to do, except the wire is internal...

See also:
https://referencesource.microsoft.com/#mscorlib/system/runtime/serialization/formatters/binary/binarycommonclasses.cs,24c9c0bbe556d44b

**Comment by PlatinumLyfe** [comment]
I assume you guys look at CoreRT ?
https://github.com/dotnet/corert

Seems there could be a lot of overlap between the two, because they compile for native operation on any OS - which means they've probably had to deal with a lot of the issues you have on converting C# to CPU commands/assembler.
