### ISSUE TITLE
how can I boot my cosmos project from a external device like flash memory or cd

### ISSUE THREAD

**Issue by EddyWilmer** [CosmosOS/Cosmos#112]
I finished to write my code, now I want to run my cosmos os from an external device like flash memory or cd

**Comment by ARMmaster17** [comment]
@EddyWilmer,
1. Open up Visual Studio and open your project
2. In solution explorer, you should see two project: *YourProjectName* and *YourProjectName*Boot. Right-click on the one that ends in **Boot**. Then click on properties.
3. You will see a list of options of how to deploy your OS. Click on an option, **CLICK SAVE**, then rebuild your project. When it's done building, the appropriate tool will launch.
Unfortunately, as far as we know of, USB mass storage deployment is broken. The ISO option works fine. Be sure to set your project to the "release" instead of "debug" build profile. Otherwise you will be stuck at the "waiting for debugger..." screen. If you get an error when you build using the PXE setting, follow the steps above, then look for a *PXE* tab. On that tab should be a textbox with an IP address. Replace that with your machine's IP address(local). If you don't know it, open command prompt and type this in:

    ipconfig /all

Sorry if that was a lot, hope this helps!

**Comment by ARMmaster17** [comment]
@EddyWilmer Your best bet would probably be to try the PXE option first. That way you don't have to burn a new CD each time or rewrite a flash drive. All you have to do is have an Ethernet connection on both your computer and a testbed computer. SImply plug both computers into a router, then follow the directions above to start the PXE server. Once the PXE server is running, turn on your computer and navigate to the BIOS. How you do this step varies depending on what kind of motherboard you have. Set your computer to *Network Boot* first before looking for bootable hard drives and disc drives. Then save your changes and reboot. You should see your OS appear after a reboot and the testbed computer fetches it from the PXE server.

**Comment by EddyWilmer** [comment]
I have to burn a cd only with the iso file, right?

**Comment by EddyWilmer** [comment]
Thank you, I'm going to try it

**Comment by EddyWilmer** [comment]
I burnt a cd with my project and I booted the cd, it show me a message : loading cosmos.bin..... After the message it show black screen

**Comment by mterwoord** [comment]
We currently have a bug with ATA. See #113

**Comment by EddyWilmer** [comment]
Thank you, It works fine!

**Comment by ARMmaster17** [comment]
@EddyWilmer If your original issue has been resolved, be sure to click *Close Issue*.

**Comment by AppLoginCreator** [comment]
Hello, I am having an issue booting from the iso. I have burned it to an optical disc, However when I boot from it it pauses on the line "Creating ATA IOGroup".  Please reply soon
Thank you,

Email: applogincreator@gmail.com

Screenshot:
https://cloud.githubusercontent.com/assets/15154772/10537427/933b0f3a-73a6-11e5-99a7-32d844e202d6.jpg

**Comment by mterwoord** [comment]
The ATA support still has some bugs related to non-implemented situations. At this moment, we're focusing on virtual environments.

What version of cosmos are you using?

**Comment by AppLoginCreator** [comment]
I am using conmoos version  CosmosUserKit-20150918-vs2015.

**Comment by AppLoginCreator** [comment]
I am using cosmos version CosmosUserKit-20150918-vs2015.

**Comment by AppLoginCreator** [comment]
Also, I can boot the same ISO on VMware. It is when I boot on hardware that I encounter this issue.

**Comment by MyvarHD** [comment]
This is a a problem right now, @CSharpLover Has a really nice rig for debugging on real hard wear, if he is up for it we can take the time and start commenting code out to find the problem with the ata driver, because he really wants to boot cosmos on real hardware to.
