### ISSUE TITLE
generic installer

### ISSUE THREAD

**Issue by furesoft** [CosmosOS/Cosmos#1199]
could you implement a generic installer to install my custom os to the disk? so this will be a common task it would be useful if it is in the framework

**Comment by MLXProjects** [comment]
Think about CosmOS doesn't even manage hard disks very well, also the VirtualFS subsystem is very buggy and doesn't work properly.
Something like a OSInstaller needs all of that working fine before being realisable, mostly because you can't write something to a HDD that you can't detect (d'oh)
Also, CosmOS File System support is very early and anything that we can test right now would not work in the future as the project updates and gets fixed.

**Comment by KM198912** [comment]
it is possible to install cosmos on a hard drive, though it needs some fiddling and tools, here is how i did it: 
First you need a Sata/IDE to Usb Adapter, i am using on of these: [https://cdn.alza.de/ImgW.ashx?fd=f3&cd=JP167](url)

Next write the ISO to the now external drive using Rufus (i tried linux DD and it didnt work for me)

ok, halfway there, nex step is optional but worked fine for me, boot into a linux live distro, i used http://www.system-rescue-cd.org/ , on the shell type "startx" and fire up gparted, create a fat32 partition on the usb drive, make sure not to touch the boot partition, power down the machine and place the hard drive back in the boot machine, by now you should have cosmos running with 2 partitions 0:\ and 1:\ my cosmos is setup to use 1:\ so i dont mess up my boot partition, keep in mind on some machines using SATA cosmos might boot but not detect the partition.

**Comment by MLXProjects** [comment]
You can even multi-boot Cosmos with Windows if you want, you just need to install Grub4DOS (or almost any bootloader) in the HDD's MBR and configure it to chainload BootMGR or CosmOS.bin
Personally, I use Grub4DOS because it's simple to modify and can boot almost everything that has boot code in it. You can even mount files to RAM and make virtual units!
