### ISSUE TITLE
Cosmos ISO not working

### ISSUE THREAD

**Issue by sudopigeek** [CosmosOS/Cosmos#1222]
I just installed the latest userkit on visual studio 2019, created a test project, and built an .iso image file.  It runs fine in Visual Studio, but if I make a virtual machine in vmware using the generated .iso file, I get this:
![testOS](https://user-images.githubusercontent.com/37987178/64891639-5afb5480-d627-11e9-9505-0fa06f3bf508.png)

**Comment by KironDevCoder** [comment]
just simply not use VMWare, VMWare doesn't really like CosmosOS

**Comment by motosoftos** [comment]
Hey there, it seems that you have not built the project properly. it means that inside the .ISO (.iso is a virtual CD), there is nothing. try rebuilding.

**Comment by motosoftos** [comment]
you might have created the ISO file with any other bootable iso maker. This dont work because you have not set testOS.bin in a correct way. to create an ISO file with Visual Studio itself :-

1) Goto Properties
2) In that, click Cosmos New (in left panel)
3) change the option to ISO
4) save.

Now if you build, you will get an iso in your project's Bin folder.

**Comment by sudopigeek** [comment]
I have already set those porperties, and the above image is from the ISO disk image file that Cosmos made.  I even replaced the virtual disk for the OS picture above with the "Filesystem" disk that comes with Cosmos, but that doesn't work either.  Any suggestions?

**Comment by sudopigeek** [comment]
I think I know what the problem is, but it is a strange bug that no one else seems to have: https://github.com/CosmosOS/Cosmos/issues/1062
The weird part is that the above issue didn't exist in the older Cosmos userkits that were for Visual Studio 2017.

**Comment by HStei** [comment]
Hello all,
I have the same Problem!
Is there a bug Fixing avaible? Or some other Solutions?

Best regards

**Comment by LeonardoBaldazzi** [comment]
@HStei try to make the iso manually

**Comment by motosoftos** [comment]
@LeonardoBaldazzi, impossible. You must be an OS master. You should create your own bootloader to boot that file. Or else, you should edit boot.bin. instead of using cosmos, I would strongly suggest you to stop using cosmos and do it on your own. There are many online resources. I too was first doing it with cosmos, then stopped and started my own. You will never get the experience and knowledge of computers and operating systems if you use things such as cosmos. You need to know many info on hardwares to build os, you cannot skip them. You must first build it with low level language.
Sorry, I went too long.

**Comment by thisisprasad** [comment]
> you might have created the ISO file with any other bootable iso maker. This dont work because you have not set testOS.bin in a correct way. to create an ISO file with Visual Studio itself :-
> 
> 1. Goto Properties
> 2. In that, click Cosmos New (in left panel)
> 3. change the option to ISO
> 4. save.
> 
> Now if you build, you will get an iso in your project's Bin folder.

This worked for me. Thank you. :)

**Comment by AcaiBerii** [comment]
With the latest userkit release there is no option under cosmos new for isos.
