### ISSUE TITLE
How to set up networking? How to host a local website?

### ISSUE THREAD

**Issue by burgerlX** [CosmosOS/Cosmos#1231]
(this os needs to host a website)
sorry, newbie

Basicaly, i need to add networking to my os,
but i can't find any example in c#.
Could anyone give me any examples or codes?

**Comment by sudopigeek** [comment]
Hosting a website in Cosmos is more difficult than you might think because of the lack of libraries it can compile compared to an "ordinary" C# application (i.e. Console application)
I would suggest going to gocosmos.org's list of Cosmos-made OSs such as Aura OS. The Aura OS project has a network driver that you can look into, but, as a newbie, the amount of code that makes up the driver will might overwhelm you (is is several hundred lines long), unless you are a TCP/IP and networking protocol expert. If you do make something based off of that code, make sure you are using the right kit (I think the Aura OS project is written in the Devkit)

**Comment by burgerlX** [comment]
Thank you,
I will certainly look into Aura OS.

**Comment by burgerlX** [comment]
> Hosting a website in Cosmos is more difficult than you might think because of the lack of libraries it can compile compared to an "ordinary" C# application (i.e. Console application)
> I would suggest going to gocosmos.org's list of Cosmos-made OSs such as Aura OS. The Aura OS project has a network driver that you can look into, but, as a newbie, the amount of code that makes up the driver will might overwhelm you (is is several hundred lines long), unless you are a TCP/IP and networking protocol expert. If you do make something based off of that code, make sure you are using the right kit (I think the Aura OS project is written in the Devkit)


Could you give me an example of something more readible? Also, shouldn't cosmos have a documentation how to set up basic networking?

**Comment by sudopigeek** [comment]
Unfortunately, Cosmos currently doesn't have anything about networking in the documentation; the Cosmos team is more focused on the kernel and debugger.  Cosmos has been around for a little while, but if you compare it with other operating systems available (Windows, Linux, etc.), Cosmos either has little of or lacks several components.  Although a full network driver would certainly be useful, Cosmos currently only has basic network libraries, which means that the end user (like you or me) has to write excessive code  for a seemingly simple purpose compared to pre-built libraries that exist in Visual Studio's other C# projects.  That is why Aura OS's network driver is so large.  I don't blame the Cosmos team for not doing much for networking; building an operating system requires years of experience in C, C++, and Assembly, and frankly, the Cosmos team is doing a good job for C#.  Remember, Cosmos is "operating system legos." There is so much that a operating system can potentially do, but it takes a lot of work because of all the low-level drivers and components that must be written; you can't just import or add a reference to a library like you can in other projects.  That is the main downside with building an operating system.  Cosmos makes it easier, but some functions are more supported than others, and the ones that are less supported you have to write the code for until the Cosmos team adds more functionality to their packages.

If you don't want to write such quantities of code for a network driver but still want a web server, write a web server program using code from [here](https://www.c-sharpcorner.com/article/creating-your-own-web-server-using-C-Sharp/) into a C# .NET Framework Console Application (or, if you prefer, a Windows Forms application from [here](https://tutorials-raspberrypi.com/write-raspberry-pi-gui-apps-c-sharp-dot-net/)) in Visual Studio.  If you don't want to run it on your own computer or don't have another computer to run it on, get a [Raspberry Pi](https://www.raspberrypi.org/) and install Mono (which is a Linux package for running .NET on Raspberry Pi, installation instructions [here](https://www.mono-project.com/download/stable/#download-lin-raspbian)), copy your executable to the Raspberry Pi, and run it.  If you aren't familiar with the Raspberry Pi, it is a small, lightweight computer that only costs $35 and is used in a variety of both physical and digital projects.  You can buy it in a full package [here](https://www.adafruit.com/product/3058), or you can install the OS (Raspbian) yourself (instructions [here](https://thepi.io/how-to-install-raspbian-on-the-raspberry-pi/)).  Raspbian isn't quite as customizable as Cosmos, but it is probably a close second and should serve your purpose well.

**Comment by burgerlX** [comment]
@sudopigeek Thanks,
i will try that.

*i also know what a pi is
