### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by CSharpLover** [CosmosOS/Cosmos#145]
Hi. In the homepage, i saw a "Fat Work" tag.
Is fat working now?
Can we use System.IO functions?

Filesystem is too important for me. Without a filesystem, an operating system is not a real operating system.

If FAT is not fully implemented, can we use ext2? If we can use, how to ext2 filesystem in lastest cosmos devkit?

**Comment by ARMmaster17** [comment]
@CSharpLover,  Filesystem support is underway. We've only got one guy working on it. It is nearing completion, but there is still a little ways to go. Even when it is finished, we are awaiting a few ATA bugs that need to be resolved first among a few other things. And when it is implemented, most likely only FAT16/32 will be supported. EXT2 Journaling filesystem will probably have to come later.

As for the importance of the filesystem in an OS, if you **really** need it, it's not that difficult to implement a live filesystem that stores data in the RAM. You may encounter a few issues if your OS is running for a long time since the memory manager isn't fully operational yet. I could walk you through it if you need help. You can find me on [Gitter](https://gitter.im/ARMmaster17).

=====
If your issue has been resolved, please click *Close Issue*. Hope this information helped!
