### ISSUE TITLE
FileSystem Error

### ISSUE THREAD

**Issue by ezic34** [CosmosOS/Cosmos#1457]
Hello guys! When I do something with the file system (get a list of files or get free space) on my OS, I get this error:
[Screenshot_102](https://user-images.githubusercontent.com/70113185/90988331-aee21d80-e59a-11ea-8930-bf65ee6b60f2.png)
It's the same when I write 0: \\. I could not find an answer on the Internet. Thanks in advance and sorry for my english
!

**Comment by ezic34** [comment]
my virtual machine is virtualbox

**Comment by ezic34** [comment]
![Screenshot_104](https://user-images.githubusercontent.com/70113185/90988790-38dfb580-e59e-11ea-8d23-46cdc6e18ada.png)
i fixed it by formatting the virtual disk but now i get this problem:

**Comment by elkaamee326** [comment]
Don't use Virtualbox. It isn't fully supported. Use VMware instead and make sure that the virtual hard disk image is Filesystem.vmdk replace your current .vmdk with this:
https://github.com/CosmosOS/Cosmos/raw/master/build/VMWare/Workstation/Filesystem.vmdk (if you are using VirtualBox).
If you debug on Visual Studio 2019 and the current selected tab is VMware than it will have it on the virtual machine by default.

To change the tab to VMware instead of ISO image in COSMOS. You need to double click on the COSMOS icon, than click properties. You will see a bunch of options and click on VMware, than press ctrl + shift + s and than try debugging and see if you still get those debug errors. It is highly recommended you use VMware.

**Comment by elkaamee326** [comment]
And also in your code do not use 1:\ use 0:\
