### ISSUE TITLE
[Filesystem BUG] The loaded file is incorrect

### ISSUE THREAD

**Issue by nifanfa** [CosmosOS/Cosmos#1464]
![QQ截图20200830101855](https://user-images.githubusercontent.com/54205437/91650093-b7ac8500-eaad-11ea-931a-9327fa84230d.png)
![QQ截图20200830102249](https://user-images.githubusercontent.com/54205437/91650096-bda26600-eaad-11ea-89e7-ea5704cbd32b.png)

**Comment by nifanfa** [comment]
And there's another unsolved problem #1458

**Comment by nifanfa** [comment]
The picture i want to load is wallpaper.bmp but it loaded the sierra.bmp and timg.bmp

**Comment by nifanfa** [comment]
and them mixed up

**Comment by quajak** [comment]
Can you please post the picture/files used directly, the easier we can recreate the problem, the easier it is to debug it.

**Comment by nifanfa** [comment]
[Workstation.zip](https://github.com/CosmosOS/Cosmos/files/5147018/Workstation.zip)
@quajak  unzip this file and put it to C:\Users\your user name\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation

**Comment by nifanfa** [comment]
[CosmosKernel1.zip](https://github.com/CosmosOS/Cosmos/files/5147020/CosmosKernel1.zip)

**Comment by elkaamee326** [comment]
So what you need to do because this worked for me is erase everything in `C:\Users\your user name\AppData\Roaming\Cosmos User Kit\Build\VMware\Workstation` replace it with the contents of `Workstation.zip`, because in the `Graphics.cs` file, in the `drawImage()` function, it loads / copies whatever is in the ram and it draws it onto the display interface. So basically, cache from other images / data stays there when you try to load to different images. Ie: `wallpaper = new Bitmap("0:\wallpaper.bmp");` and change the same line of code to: `wallpaper = new Bitmap(0:\a-different-bmp.bmp);` Because when I tried the code it worked perfectly fine for me (no image loading glitches).
