### ISSUE TITLE
Exeption: Unable to determinate filesystem for path 0:/

### ISSUE THREAD

**Issue by HStei** [CosmosOS/Cosmos#1536]
Hello,

I used the ISO file, vmware bootet from.
Then I "burned" it with Rufus on my usb stick.

I created a FAT partition next to Windows 10 on internal ssd on my laptop.
But the error comes up, when cosmos os bootet: Exeption: Unable to determinate filesystem for path 0:/

Do you have any ideas?

Here is a screenshot of my partitions on laptop:
https://ibb.co/M741SHc 

P.S.: In VMWare everything works fine, creating files, reading files and so on...
Thank you!

**Comment by quajak** [comment]
The problem is that the first partition on the ssd is not a fat32 partition and cannot currently be accessed by cosmos. Since the addressing of partition/file systems is regardless of whenever the fs can be read, `0:` will try read the first partition on the disk which wont work in your case. To get the list of intialised partitions use GetVolumes(), from there you can determine which filesystem root you should use, i.e. use `1:` not `0:`.

Another option is to ensure that the first partition is of type fat32.
