### ISSUE TITLE
CosmoOS

### ISSUE THREAD

**Issue by ilobilo** [CosmosOS/Cosmos#1663]
Can i download CosmosOS dlls to use them without visual studio?
Like in c# shell on android?

**Comment by elkaamee326** [comment]
Unfortunately, it requires Visual Studio 2019 to function properly, because it needs to compile your kernel first into .net IL code (.dll). After that, it it uses `IL2CPU.exe` to turn that `.dll` into an assembly file or bootable code (.asm). After it runs NASM (Netwide Assembler), so that it can compile the `.asm` bootable code into a standard .bin file. After that, depending on your selection, in the properties menu, it sets up that desired selection... Ie: VMware debug, Bochs, Hyper V, ISO Image etc.... As you can see, you require an Operating System (Host) that can run `.exe` files and link dlls, in order to build and debug; like Windows. So, I think sticking with Visual Studio 2019, would be your best bet. Also, COSMOS, designed their sdk to integrate with Visual Studio, not any other IDE, so this should answer your question.

**Comment by ilobilo** [comment]
Thanks!
