### ISSUE TITLE
Exception: System.Exeption When Using DateTime.Now.ToString("HH:mm");

### ISSUE THREAD

**Issue by Vardan2009** [CosmosOS/Cosmos#1692]
#### Area of Cosmos - What area of Cosmos are we dealing with?

Date And Time

#### Expected Behaviour - What do you think that should happen?

Show Date And Time

#### Actual Behaviour - What unexpectedly happens?

Shows This (Exception: System.Exception)
![Screenshot 2021-03-09 190024](https://user-images.githubusercontent.com/70532109/110490922-3263f600-810a-11eb-81e3-b16102329aee.png)

#### Reproduction - How did you get this error to appear?

![Screenshot 2021-03-09 190125](https://user-images.githubusercontent.com/70532109/110490980-427bd580-810a-11eb-8b8e-6fa75b76d614.png)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
UserKit

**Comment by zarlo** [comment]
can we get a stack trace

**Comment by MishaTY** [comment]
A plug is needed for DateTime.ToString(string). Try using DateTime.Now.ToString() instead of DateTime.Now.ToString("HH:mm")

**Comment by Vardan2009** [comment]
Yeah I use DateTime.Now.ToString();

But why DateTime.Now.ToString("HH:mm"); isn't working?

**Comment by elkaamee326** [comment]
They haven't implemented the function for `DateTime.Now.ToString("HH:mm");`, but `DateTime.Now.ToString();` is pretty much the same thing. Because the `HH:mm` is just to tell the function that it is a 12hr clock and not 24 and the one that is currently implemented just displays all the durations of time instead of specifying the parameters, ie: Century, Year, Month, Day, Hour and Second. So, in order to implement it you must communicate with the RTC and tell it to display a 12hr clock and not a 24hr clock.

**Comment by Vardan2009** [comment]
I know that
