### ISSUE TITLE
MP3 Player ?

### ISSUE THREAD

**Issue by ArtGo-Devloppper** [CosmosOS/Cosmos#1710]
**What is the usecase for this plug**
For sounds or a music app

**Describe alternatives you've considered**
no, not to my knowledge

Hello, I suggest an mp3 (or wav) driver to play sounds or music.
Did Cosmos have a method to play sound?
Thanks

**Comment by MishaTY** [comment]
Cosmos does not currently support playing sounds, but you can write your own driver and play mp3s.

**Comment by ArtGo-Devloppper** [comment]
Thanks, but is there a way to play mp3 (or wav) files and use Cosmos.System.PCSpeaker.Beep((uint)Cosmos.System.Notes.B5, 432); like in AuraOS ?

**Comment by MishaTY** [comment]
No, PCSpeaker.Beep only supports 1 frequency at a time.

**Comment by elkaamee326** [comment]
@ArtGo-Devloppper , Cosmos doesn't have a "fully complete" implementation of sound, but if you want to play basic pcm audio you can try to use this example (This is the closest we can get for now to playing real pcm audio. Settings: Unsigned 8-bit pcm wav with a 16khz sampling rate and it has to be mono):     Also, the IRQ is unstable and wav files aren't supported in that implementation. I am currently working on optimizing and fixing the code so that "real sound" can be played and not just audio data converted into a byte array and to maybe fix the IRQ, if possible. 

Also, @MishaTY, in the dev kit, for loading the audio data in wav files is `File.ReadAllBytes();` supported / fixed? In the Userkit, it threw an implicit exception stating that Enum.ToString() is not implemented.

**Comment by elkaamee326** [comment]
@ArtGo-Devloppper, loading MP3 files are much harder than loading wav, because for an MP3 implementation you have to use compression and decompress it, whereas `.wav` files are already uncompressed and you just need to convert the binary data into their integral values to make a `.wav` codec.

**Comment by quajak** [comment]
I am closing this since @elkaamee326 has given a very good overview of the current state of work on audio. For further questions on audio or similar questions in general please use the discussions feature. 
@elkaamee326 File.ReadAllBytes is still broken for very large files but should otherwise work.
