### ISSUE TITLE
Errors while installing DevKit

### ISSUE THREAD

**Issue by NETdeve** [CosmosOS/Cosmos#1732]
Hello. I am using UserKit. I'd like to upgrade to DevKit (i run installvs2019.bat) it opens cosmos kit builder and it starts building. At the end of this process it gives me some errors:

System.Exceptions: The process failed to execute!
 at Cosmos.Build.Builder.BuildTasks.processbuildtaskbase.WaitForExit(Process process) in C:\Cosmos-master\cosmos-Master\source\Cosmos.build.Builder\BuildTasks\ProcessBuildTaskBase.cs line 67

and others error.
How can I solve? Thanks in advance!

**Comment by MishaTY** [comment]
See https://github.com/CosmosOS/Cosmos/issues/1100

**Comment by NETdeve** [comment]
Thanks @MishaTY.
The problem still remain, i unlocked all the zip and re-extracted. It gives same errors: ( system.exception: the process failed to execute! at cosmos.build.builder.buildtasks.processbuildtaskbase.waitforexit(Process process) in ..\Cosmos-master\Cosmos-master\source\Cosmos.Build.Builder\BuildTasks\ProcessBuildTaskBase.cs


thanks in advance

**Comment by MishaTY** [comment]
Did you unblock Cosmos\source\Cosmos.VS.ProjectSystem\ProjectSystem\VS\PropertyPages\OldCosmosPropertyPageControl.resx?

**Comment by NETdeve** [comment]
No, i couldn't. There wasn't the option.

**Comment by MishaTY** [comment]
Can you post the full build log?

**Comment by quajak** [comment]
Rename Cosmos-master to Cosmos

**Comment by quajak** [comment]
@MishaTY Regardless of the actual error the builder will end with `System.Exceptions: The process failed to execute!
at Cosmos.Build.Builder.BuildTasks.processbuildtaskbase.WaitForExit(Process process) in C:\Cosmos-master\cosmos-Master\source\Cosmos.build.Builder\BuildTasks\ProcessBuildTaskBase.cs line 67` To determine the actual error one has to get the full log (or at least the last section which has the actual error).

**Comment by sudopigeek** [comment]
The files in the devkit have what is called an Alternate Data Stream (ADS) named "Zone.Identifier", which stores information about where the file came from. Because the devkit files were downloaded from the internet, Windows blocked them as a safeguard. Since the devkit files are safe, though, you need to remove the flag from the files:

1 - Download Streams from [here](https://docs.microsoft.com/en-us/sysinternals/downloads/streams).
2 - Extract the ZIP file and copy streams.exe to your Cosmos devkit root directory.
3 - Open a command prompt, navigate to where you put the executable, and type `streams -s -d`.

After streams has removed the flags, you should now be able to run installvs2019.bat. Before you run it, you should uninstall the userkit so Visual Studio doesn't get confused.

**Comment by NETdeve** [comment]
Hello. I fixed the problem renaming the folder from cosmos-master to cosmos. Thanks @MishaTY @quajak @sudopigeek
