### ISSUE TITLE
Keyboard not working correctly

### ISSUE THREAD

**Issue by SuperMatejCZ** [CosmosOS/Cosmos#1801]
#### Area of Cosmos - What area of Cosmos are we dealing with?
In OS(after boot)

#### Expected Behaviour - What do you think that should happen?
Keyboard work normally

#### Actual Behaviour - What unexpectedly happens?
Keyboard not in QWERTY. (Keys arel mapped incorrectly)

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Latest wersion of Dev Kit

**Comment by quajak** [comment]
So you are using a QWERTY (standard english) keyboard but they keyboard mapping is not correct?

**Comment by SuperMatejCZ** [comment]
Yes

**Comment by AnErrupTion** [comment]
You can change the keyboard layout with the KeyboardManager class, but this is a bug nonetheless.

**Comment by quajak** [comment]
What keys are being mapped incorrectly?

**Comment by SuperMatejCZ** [comment]
All (A is Enter)

**Comment by quajak** [comment]
I am assuming this is on real hardware? Is the keyboard an actual ps/2 keyboard?

**Comment by SuperMatejCZ** [comment]
1. Yes
2. No (I am using notebook)

**Comment by quajak** [comment]
Looking at https://github.com/CosmosOS/Cosmos/blob/master/source/Cosmos.HAL2/PS2Keyboard.cs it seems like we could be using the wrong scan code set. Since you are using the devkit, could you maybe add `Console.WriteLine("(PS/2 Keyboard) Current scan code set: " + GetScanCodeSet());` to the Initialize method and see what it returns?

**Comment by AcaiBerii** [comment]
No user response moment
