### ISSUE TITLE
Error during debugging: Could not load file or assembly System.Runtime, Version=5.0.0.0

### ISSUE THREAD

**Issue by theLMGN** [CosmosOS/Cosmos#2115]
**Exception**
```
Unexpected exception during Attach System.IO.FileNotFoundException: Could not load file or assembly System.Runtime, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version= 5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a* Cosmos.VS.DebugEngine.AD7.Impl.AD7Process..ctor(Dictionary'2 aDebuginfo, EngineCallback aCallback, AD7Engine aEngine, IDebugPort2 aPort)
at
Cosmos.VS.DebugEngine.AD7.Impl.AD7Engine.Microsoft.VisualStudio.Debugger.Interop.IDebugEngineLaunch2.LaunchSuspended(String aPszServer, IDebugPort2 aPort, String aDebuginfo, String aArgs, String aDir, String aEnv, String Options, enum_LAUNCH_FLAGS aLaunchFlags, Ulnt32 aStdInputHandle, Ulnt32 aStdOutputHandle, Ulnt32 hStdError, IDebugEventCallback2 aAD7Callback, IDebugProcess2& Process)
WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value
```

**To Reproduce**
Debug a Cosmos Kernel

**Screenshots**
![image](https://user-images.githubusercontent.com/12257112/153714708-513faba6-dd55-4e00-97b1-d821548dfdcb.png)

**Context**
Before posting please confirm that the following are in order
[x] Both Cosmos VS Extensions are installed
[x] In the NuGet Package Manager "Include prerelease" is selected
[x] The Cosmos NuGet package store is selected (NOT nuget.org) in 'Manage NuGet Packages'
[x] The Cosmos NuGet packages are installed

This happens on a fresh install of Windows 10.

**Comment by pto-buon** [comment]
Try to uninstall cosmos, vmware and reinstall them

**Comment by kevld** [comment]
I had the the same issue, I put the Common, CosmosOS, IL2CPU, XSharp and my solution folders into my D drive.
I also never launched VMWare. So this is what I did : 
1) Launch VMWare to enable it and activate a free licence
2) Moved Common, CosmosOS, IL2CPU, XSharp into C:\source\CosmosOS as said in the docs (i wanted to try an other folder because all my stuff is on the D drive...) 
3) run install-VS20XX.bat in powershell Admin mode
4) in %AppData%\Roaming\Cosmos User Kit\VSIX, install the two .vsix files
5) Create a Cosmos projet in VS (tried to save it on C and D, both worked)
Then It worked ! 

Hope it helps
