### ISSUE TITLE
Implement string[] in the debugger.

### ISSUE THREAD

**Issue by ghost** [CosmosOS/Cosmos#23]

**Comment by Kiirx** [comment]
Bro 7years ago this can be closed

**Comment by husaral2** [comment]
I tried to do it, but I don't know how to test it because I don't know how to use the debugger.
Here is the updated files, you can test it by replacing the files, rebuilding Cosmos and trying to use the debugger function which takes string[].
[Files.zip](https://github.com/CosmosOS/Cosmos/files/10951646/Files.zip)

**Comment by quajak** [comment]
Thanks for your work! Can you please open a pull request so we can discuss it further and merge it when its ready?

**Comment by 9xbt** [comment]
This was fricking 8 years ago, and it still hasn't been closed yet

**Comment by quajak** [comment]
This was fixed by https://github.com/CosmosOS/Cosmos/pull/2603
