### ISSUE TITLE
The installer gets the default path wrong.

### ISSUE THREAD

**Issue by SkyyySi** [CosmosOS/Cosmos#2329]
**Describe the problem**

When installing Cosmos v2022, the installer chooses the wrong default path. In my case, it was `D:\Computer\AppData\Roaming\Cosmos User Kit` instead of `C:\Users\<USER>\AppData\Roaming\Cosmos User Kit`. Continuing the installation with that path will result in Cosmos not working, with it (almost?) immediately stops building of the OS.

**Steps of installation up to now**

Install `CosmosUserKit-20220209-vs2019.exe` from the releases tab without changing the default path. This is most likely a situational bug. Perhaps it is related to having a `D:\` drive or multiple drives attached, or perhaps it has something to do with having a previous version of Cosmos installed (just a guess).

Importantly, changing the default path to `C:\Users\<USER>\AppData\Roaming\Cosmos User Kit` manually fixes this. This may mean that the path shown in the installer is not what Cosmos will configure its files for. I mean this in the sense that it may move a file to `D:\...`, but the paths mentioned in the configuration point somewhere else.

**Expected behavior**

The default path should be the same as in v2020 (i.e. `C:\Users\<USER>\AppData\Roaming\Cosmos User Kit`) and it should work without being changed.

**Logs**
https://cdn.discordapp.com/attachments/833978908189392916/996029511273558096/unknown.png

**Steup (please complete the following information):**
 - Cosmos version ⇾ Userkit (CosmosUserKit-20200708-vs2019)
 - Are you using an admin account? ⇾ No
 - VS Version if applicable ⇾ Microsoft Visual Studio Community 2019 Version 16.11.16

**Comment by zarlo** [comment]
cosmos needs to be installed in "C:\Users\<USER>\AppData\Roaming\Cosmos User Kit" there are some hard coded paths

**Comment by ptobuon** [comment]
And yes, Cosmos need to be installed in C:\Users\%userprofile%\AppData\Roaming\Cosmos User Kit.

**Comment by quajak** [comment]
> I think you need to use an admin account to install cosmos

No, you will need admin permissions when installing for the visual studio extensions but the account does not need to be an admin. Cosmos will assume that the Cosmos User Kit is in the %appdata% of the current user.

**Comment by Arawn-Davies** [comment]
I've got the same issue running on Windows Server 2019 & 2022, can confirm it does erroneously default to ```D:\Computer\AppData\Roaming\Cosmos User Kit\```

**Comment by quajak** [comment]
I think I figured out the issue. The current approach was implemented by https://github.com/CosmosOS/Cosmos/commit/cf56bb9eec1bb87b10dbe95407b81de25aab078c to improve how the local appdata path was found and it works on the local machine perfectly when building user- or devkit. The issue is that the path is hardcoded when compiling so the person who compiles the userkit determines what the default path will be for all installations. Most likely a better solution will be to just use `{userappdata}` and accept that this will give the wrong path in certain cases (at least it will usually be correct). 

@valentinbreiz Thoughts on this, since you did the last change
