### ISSUE TITLE
Executable files

### ISSUE THREAD

**Issue by dm-vev** [CosmosOS/Cosmos#2345]
How can I run .dll (or some other format) files? And is it possible to run the application in this way on the one assembled on IronPython?

**Comment by ascpixi** [comment]
Running native executable code requires you to create your own PE parser and some basic execution code using X# - a good example is [this pull request from the Aura Operating System](https://github.com/aura-systems/Aura-Operating-System/pull/244/). As for running IL DLL files, no such thing is implemented in Cosmos out-of-the-box; however, you can write your own implementation of the CLR and a JIT-ter (or alternatively, an interpreter, which would be slower but easier to implement). There's an existing [IL interpreter made by MishaTY](https://github.com/mishaTY/DotNetParser), that includes a PE parser so that you can run DLL files directly.

However, if you're going for native execution, you will of course need to write executables that are native to your operating system, as system calls differ from OS to OS. The CIL doesn't have this issue, but you will have to implement a good chunk of the core library yourself.

**Comment by dm-vev** [comment]
Thank you, just 10 minutes ago I came across this very useful library. I think in current realities, this is the best way to make "apps".

**Comment by dm-vev** [comment]
closing
