### ISSUE TITLE
I'm trying to import a bitmap from file into a bitmap class

### ISSUE THREAD

**Issue by winbamstudios** [CosmosOS/Cosmos#2385]
I need help with importing a bitmap file into a bitmap with cosmos userkit

**Comment by ascpixi** [comment]
If you want to load a .BMP file in Cosmos, you'll need to use the `Bitmap` constructor that accepts a single `byte[]`:
```cs
var bitmap = new Bitmap(bmpBytes);
```
Keep in mind that this approach does not work for compressed bitmaps; if you want to do that, you'll have to write your own BMP decoder.
In order to get the byte array, you can either read from the ISO or embed the file using the `ManifestResourceStream` attribute:
```cs
[ManifestResourceStream(ResourceName = "(name of your os).MyImage.bmp")]
readonly static byte[] bmpBytes;
```
The above example will load the bitmap named "MyImage.bmp" located at the root directory of your project (usually where the .csproj file is located).

**Comment by winbamstudios** [comment]
thanks :)
