### ISSUE TITLE
[question] how to get CPU and RAM load in percentage?

### ISSUE THREAD

**Issue by koteProgrammist** [CosmosOS/Cosmos#2567]
Please, i need to get CPU and RAM load in percentage

**Comment by Jspa2** [comment]
CPU load is rather pointless as Cosmos is single threaded and not a multitasking kernel. RAM usage however can be  determined with the `Cosmos.Core.GCImplementation.GetUsedRAM()` and `Cosmos.Core.CPU.GetAmountOfRAM()` methods.

Example:
```csharp
var ramUsage = (Cosmos.Core.GCImplementation.GetUsedRAM() / 1024 / 1024) / Cosmos.Core.CPU.GetAmountOfRAM();
```

The *used RAM* is divided to convert it to the correct unit, since the latter method is in megabytes rather than bytes.
