### ISSUE TITLE
Cosmos C# Kernel projects builds unexpectedly large ISO

### ISSUE THREAD

**Issue by SevenworksDev** [CosmosOS/Cosmos#2917]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Building ISO

#### Expected Behaviour - What do you think that should happen?
For the ISO file to be below 15MB

#### Actual Behaviour - What unexpectedly happens?
File is around 30MB

#### Reproduction - How did you get this error to appear?
Used the Cosmos BasicTerminalShell template and built it on Visual Studio 2022

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit (Cosmos, IL2CPU, X#)?
Cosmos User Kit 20221121

#### GitHub Repo of where OS files are located
https://github.com/SevenworksDev/SimpleOS

**Comment by TheRealEli310** [comment]
I am pretty sure that's intended. Cosmos has to do a lot of things before your code can run, and that's why the ISO is 30mb. Most of that is not your code. I don't think it is possible to go lower than 30mb with Cosmos unless you modify the source code of Cosmos and remove the things you aren't using.
