### ISSUE TITLE
How do I make my OS bootable for a CD?

### ISSUE THREAD

**Issue by uNiiels** [CosmosOS/Cosmos#363]
I have made my very simple (5 minutes of work) OS. Now I want to make it bootable for a CD/USB. But if I burn it on my USB it stops at the "Loading COSMOS.bin", it says "ok" but it doesn't do anything whatsoever.
Please help me!

**Comment by uNiiels** [comment]
Sorry, but I forgot to mention that my OS does fully work in Oracle Virtualbox.

**Comment by zarlo** [comment]
what are the setting you are using in you boot project

**Comment by uNiiels** [comment]
ISO

**Comment by uNiiels** [comment]
not bootable USB or open in VMware player

**Comment by uNiiels** [comment]
Sorry that I'm reacting a bit late, but I'm from Holland. The time is different you know.

**Comment by fanoI** [comment]
Please check that your portable has not UEFI for now Cosmos support only BIOS. Unsure too that has not been compiled in debug mode or will be wait for a serial connection before starting.

**Comment by MichaelTheShifter** [comment]
Actually if he's compiling through ISO it automatically disables debug mode IIRC.

Also if he were booting through UEFI his computer would not find the OS, and just boot the next on the list. I noticed that with the same ISO from my SharpOS, it worked fine on a custom-built desktop with an AMD A10-7700K CPU, but would get stuck detecting hardware on a 2007 Toshiba Satellite with an Intel Core 2 Duo. My guess is the OP's CPU is not supported by Cosmos - or it doesn't like a piece of hardware on the system.

**Comment by yewmisgoat** [comment]
Actually, I boot mine off of USB all the time and it works just fine. I *love* COSMOS, but the documentation is.. well... lacking. Anyways, here's how to boot off of a USB. 
1. In Visual Studios with your project open, on the top bar of the IDE go to "Build -> Configuration Manager..."
2. Change "Active Solution Configuration" from "Debug" to "Release" (This is important! Otherwise it will boot on your hardware and be stuck in an endless loop at the "Connecting to debugger..." screen) 
3. Click "Start" like you normally would to test your OS, and let it build, compile, etc.
4. When it's done, look in whatever folder your project, and locate the .iso file it generated. Assuming your project was called "CosmosKernel1", it would be located within your project folder as follows: "...\CosmosKernel1\bin\CosmosKernel1Boot.iso"
5. Download [Rufus Portable](https://rufus.akeo.ie/downloads/rufus-2.9p.exe) from [rufus.akeo.ie](https://rufus.akeo.ie/). Rufus is a program for "burning" .iso files to USB drives. (I've used many, and this is by far the best I've used, and it's free) 
6. Run Rufus Portable, and it will display a WinForms-looking app. Select your Device, change the "New volume label" box to whatever you want it to name your USB. Change it from "FreeDOS" to "ISO Image". Then, click the disc icon, and select the .iso image you located in step 4. 
7. Click start. (**Warning, this *WILL* format the drive!**)

**Comment by fanoI** [comment]
Wow! So you have Cosmos runnning on real hardware? Could you add this instructions on how to create an ISO and make it bootable as USB onto the wiki? Another thing do you have tried to burn the ISO on a CD-R / DVD-R and see if Cosmos booted successfully?

**Comment by yewmisgoat** [comment]
I have not tried CD-R, but was planning on trying today. I will let you know how that goes first thing I do. :)

**Comment by yewmisgoat** [comment]
Okay, tested with a CD-RW, and tested it on both an x86 and x64. The x86 booted just fine, and is fully functioning (minus file IO, because as far as I know, COSMOS cannot find drives other than what it's booted with, in this case a CD) and the x64 never made it to the Kernel.BeforeRun() phase. As far as the USB, I got it to boot just fine on x86 as well, but again, no x64 support.

**Comment by fanoI** [comment]
OK! Well is more that I expected really...

Regarding the fact that the HDD is not found yes I imagine it is because is not mounted ask to @charlesbetros in the chat if it is possible to find and mount other disks, please note that only FAT filesystem is supported.

x64 should theoretically be supported in x86 mode probably there is some problem in the initialization phase, maybe the PC has an UEFI BIOS? UEFI is not yet supported.

**Comment by CheesyNM** [comment]
Thanks!
