### ISSUE TITLE
Mouse click event in cosmos

### ISSUE THREAD

**Issue by cosmoferrito** [CosmosOS/Cosmos#421]
Hello everyone  I am new to cosmos and am trying to build out an operating system. I want to know how to know if the user has clicked the mouse button. This has been a great problem for me.  Thanks for help in advance

**Comment by MichaelTheShifter** [comment]
This is surprisingly pretty simple. In my OS I have a class in the system ring that talks with the mouse driver, and when a mouse app is running it runs in a loop, and when the mouse button status changes it fires the relevant method. For example if the mouse state is now Left we fire something like `MouseApp.LeftClick();`. Then when it changes back to None we fire `MouseApplication.ButtonRelease();`.

Here's the code I use for my OS:

```C#
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Memphis_SystemRing
{
    public static class MouseHandler
    {
        private static Cosmos.HAL.Mouse _mouse = null;
        private static int lastX = -1;
        private static int lastY = -1;
        private static Cosmos.HAL.Mouse.MouseState lastState = Cosmos.HAL.Mouse.MouseState.None;

        public static int LastX { get { return lastX; } }
        public static int LastY { get { return lastY; } }
        public static int X { get { return _mouse.X / 2; } }
        public static int Y { get { return _mouse.Y / 2; } }
        

        public static void Start(MouseApplication app, string[] args)
        {
            if (_mouse == null)
            {
                _mouse = new Cosmos.HAL.Mouse();
                _mouse.Initialize((uint)Console.WindowWidth * 2, (uint)Console.WindowHeight * 2); //Makes the mouse half as sensitive so we don't jump around the screen like a kid on caffeine.
            }
            app.BeforeRun(args);
            app.Running = true;
            while(app.Running == true)
            {
                if (_mouse.Buttons != lastState)
                {
                    if (_mouse.Buttons == Cosmos.HAL.Mouse.MouseState.Left)
                        app.LeftButton();
                    else if (_mouse.Buttons == Cosmos.HAL.Mouse.MouseState.Middle)
                        app.MiddleButton();
                    else if (_mouse.Buttons == Cosmos.HAL.Mouse.MouseState.Right)
                        app.RightButton();
                    else if (_mouse.Buttons == Cosmos.HAL.Mouse.MouseState.None)
                        app.ButtonRelease();

                }

                if (X != lastX)
                    app.Run();
                if (Y != lastY)
                    app.Run();

                lastX = X;
                lastY = Y;
                lastState = _mouse.Buttons;
            }
        }
    }

        public abstract class MouseApplication
    {
        public MouseApplication(string[] args)
        {
            MouseHandler.Start(this, args);
        }

        public virtual bool Running { get; set; }
        public abstract void BeforeRun(string[] args);
        public abstract void Run();
        public virtual void AfterRun()
        {

        }

        public abstract void LeftButton();
        public abstract void MiddleButton();
        public abstract void RightButton();
        public abstract void ButtonRelease();
        
    }
}
```

Then what I do to start an app that uses the mouse I make the app override that MouseApplication, implement all the abstract members, then in my kernel or wherever I want the app to start I can just instantiate it using `new` and it starts automatically.

This is used for console mouse support and the mouse is drawn by the app itself, so it's probably not for your use case, but with slight modifications you could make the mouse drawn by the mouse handler, just have it draw ***after the app draws it's contents*** so it always appears on the top, and don't use Console.WindowWidth / Console.WindowHeight for the mouse bounds (and don't multiply 'em by 2 then divide the mouse x and y by 2 when accessing coordinates otherwise you'll get a slower mouse.)

Also I'm trying to port some ComputerCraft applications that use the mouse (they're entirely text-based) so that's why I put together a console mouse driver. Just sayin'.

**Comment by DjAlEx234** [comment]
only if i could use devkit...
