### ISSUE TITLE
Equals not getting plugged

### ISSUE THREAD

**Issue by jp2masa** [CosmosOS/Cosmos#473]
Char.Equals(Char) is plugged, but it's not being recognized, am I missing something? I even tried plugging System.ValueType.Equals(System.Object) and doesn't work too.

```
6>	Error: Exception: System.Exception: Native code encountered, plug required. Please see https://github.com/CosmosOS/Cosmos/wiki/Plugs). System.Boolean  System.ValueType.CanCompareBits(System.Object).
6>	 Called from :
6>	System.ValueType::Boolean Equals(System.Object)
6>	System.Char::Boolean Equals(Char)
```

I also tried this:

```
char c1 = 'a';
char c2 = 'a';

Console.WriteLine(c1 == c2); //works
Console.WriteLine(c1.Equals(c2)); //fails
```

The Char.Equals(Char) plug basically is `return aThis == aThat;`

**Comment by czhower** [comment]
Its on our list to rework plugs in the near future. Getting a sig match can be tricky, and if there is no match the compiler wont tell you, it just ignores it which is of course frustrating....

**Comment by charlesbetros** [comment]
What does your plug signature look like?

**Comment by charlesbetros** [comment]
Char equals is simple and doesn't need a plug. http://referencesource.microsoft.com/#mscorlib/system/char.cs,120 Your issue is that you are using ==. That's different. 
[PlugMethod(Signature = "System_Boolean__System_Char_op_Equality_System_Char__System_Char_")]
public static bool op_Equality(char left, char right) in that you can call left.Equals(right)

I think you'll actually need to plug it in value type but try it in char first.

**Comment by jp2masa** [comment]
So every type has a op_Equality method, and that's what should be plugged?

**Comment by charlesbetros** [comment]
I think you'll need to plug it in ValueType

**Comment by jp2masa** [comment]
I had to plug Equals in ValueType. Thanks.
