### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by DjAlEx234** [CosmosOS/Cosmos#511]
I have been trying a lot of ways to get the screen working, but it didn't work. Can I have a finished .sln file?

**Comment by MohammadSharper** [comment]
> I have been trying a lot of ways to get the screen working, but it didn't work. Can I have a finished .sln file?
Hi, I can't undreastand. you want to use GUI and VGA?
There are many examples:

**Comment by fanoI** [comment]
Are you using the VGA driver? If yes is normal... is broken sadly :-)

**Comment by DjAlEx234** [comment]
What I mean is that the forums are very scarce on info about it...

**Comment by DjAlEx234** [comment]
I have also tried pre-made ones. But I need one from the makers of COSMOS... (sorry for wasting your time)

**Comment by MohammadSharper** [comment]
I have one Cosmos OS with a gui (just mouse pointer)
I trying to convert an old example to works with new cosmos. In new version, Hardware was renamed to HAL and There's Access levels control and permissioning system that forbids accessing to hardware without calling to this system.
I will upload it after when I turn my pc on.

**Comment by DjAlEx234** [comment]
Thank you people, I'm wating

**Comment by MohammadSharper** [comment]
This isn't possible for me. Because my father (I'm only 12) moved the modem from my room to living room and I can't access to internet with my pc.
I downloaded it from net, so you can easily find it from google: GUI for Cosmos.
But there's a project called CosmosGL that can make the writing gui easier and better. This is a .NET library and you can use it by refrences.
