### ISSUE TITLE
Console.Width and Console.Height

### ISSUE THREAD

**Issue by APERSONA32** [CosmosOS/Cosmos#668]
Hey, I was wondering if there is a way for me to change the number of column and number of rows that are available on screen at the same time. I tried using the two lines mentioned in the title but it never seemed to change anything. Is there something I'm missing?

**Comment by jp2masa** [comment]
I think that the columns and rows can't be changed currently. I think that there are some well defined VGA Text Screen resolutions that can be used, but that would need to be implemented in the driver.

**Comment by APERSONA32** [comment]
Oh, okay  thank you. Should I close now?

**Comment by jp2masa** [comment]
You can keep it open as a feature request.

**Comment by APERSONA32** [comment]
okay
Thanks for the help

**Comment by sudopigeek** [comment]
Since Cosmos runs on a virtual machine and not a CMD window, the width and height currently cannot be changed using Console.Width and Console.Height. Unless you want to go to the trouble of finding and setting the screen at a specific size, it varies depending on what monitor is being used.

If you wanted to do so for the alignment of text, use the library at https://github.com/sudopigeek/CommanderLib_v1 to indent and align text in your OS.

**Comment by RMuskovets** [comment]
There are VGA text modes, all you should do is:

1. Create a `SetVGAMode` function with mode's number as argument.
2. Create a function which will:
2.1. Check for valid width & height, or round them to the nearest.
2.2. Get a VGA mode's number with that size.
2.3. Set the VGA mode
3. Add the call of that method into the setters of the fields.

P.S. Sorry for my English, I'm Ukrainian))

**Comment by RMuskovets** [comment]
> I think that the columns and rows can't be changed currently. I think that there are some well defined VGA Text Screen resolutions that can be used, but that would need to be implemented in the driver.

That resolutions can be used in the last method.

**Comment by BlitzWolfMatthew** [comment]
@quajak I think we can close this now as it has been implemented.
