### ISSUE TITLE
A File System in Cosmos?

### ISSUE THREAD

**Issue by JackHalpin** [CosmosOS/Cosmos#75]
My operating system is almost complete, but I need help with giving my operating system file reading/writing capabilities. All I'm asking for is a simple system that will allow me to write a file to... say, a floppy disk, and load its contents into memory. 

Does the latest version of Cosmos (build 108477) come with file reading/writing capabilities? If it doesn't, could somebody point me to a good user-created one?

Thank you in advance!

**Comment by mterwoord** [comment]
Currently we're fighting a bug in the compiler, which is presented similar
to what you encounter.
The issue is caused by the compiler either not emitting a given VMT entry,
or not initializing the VMT correctly...

On a side note: Please don't cross-post..


2015-04-14 2:38 GMT+02:00 Jack Halpin <notifications@github.com>:

**Comment by JackHalpin** [comment]
What does VMT stand for?

and...

What is cross-posting?

and...

sorry if I did it.

**Comment by mterwoord** [comment]
Ah, sorry. Crossposting is posting the same question in different forums.

VMT it the virtual method table. It's used for finding the correct
instances of virtual methods..



2015-04-14 13:43 GMT+02:00 Jack Halpin <notifications@github.com>:

**Comment by JackHalpin** [comment]
Thanks. Good-Bye!
