### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by sntdevco** [CosmosOS/Cosmos#780]
As soon as I open the website - I get a 404 error!
I need help with installation and the website is down. Why can't you keep a wiki at GitHub itself??

**Comment by ShalokShalom** [comment]
Confirmed

**Comment by czhower** [comment]
As per facebook, gitter, and other channels.

Urgent Notice

Updated Sep 29, 2017

The hosting service which hosts our website has a technical issue which has taken our website offline. We are urgently working to resolve this issue. We hope that our primary website will be restored today.

Hurricane Harvey

The issue is being impacted by lasting impacts to a center in Houston affected by Harvey and the impacts of moving resources out of the affected location.
