### ISSUE TITLE
Website changed?

### ISSUE THREAD

**Issue by ShalokShalom** [CosmosOS/Cosmos#782]
![screenshot_20170930_144105](https://user-images.githubusercontent.com/6344099/31045873-7340ce6a-a5ed-11e7-82f6-1d82b77cc00a.png)

**Comment by czhower** [comment]
As per facebook, gitter, and other channels.

Urgent Notice

Updated Sep 29, 2017

The hosting service which hosts our website has a technical issue which has taken our website offline. We are urgently working to resolve this issue. We hope that our primary website will be restored today.

Hurricane Harvey

The issue is being impacted by lasting impacts to a center in Houston affected by Harvey and the impacts of moving resources out of the affected location.
