### ISSUE TITLE
Website down for more than a day

### ISSUE THREAD

**Issue by sntdevco** [CosmosOS/Cosmos#783]
This is the message I got:
SORRY!
If you are the owner of this website, please contact your hosting provider: webmaster@gocosmos.org
It is possible you have reached this page because:

The IP address has changed.
The IP address for this domain may have changed recently. Check your DNS settings to verify that the domain is set up correctly. It may take 8-24 hours for DNS changes to propagate. It may be possible to restore access to this site by following these instructions for clearing your dns cache.

There has been a server misconfiguration.
You must verify that your hosting provider has the correct IP address configured for your Apache settings and DNS records. A restart of Apache may be required for new settings to take affect.

The site may have moved to a different server.
The URL for this domain may have changed or the hosting provider may have moved the account to a different server.

**Comment by mterwoord** [comment]
This is a known issue. We are working on it.

2017-09-30 14:44 GMT+02:00 sntdevco <notifications@github.com>:

**Comment by czhower** [comment]
As per facebook, gitter, and other channels.

Urgent Notice

Updated Sep 29, 2017

The hosting service which hosts our website has a technical issue which has taken our website offline. We are urgently working to resolve this issue. We hope that our primary website will be restored today.

Hurricane Harvey

The issue is being impacted by lasting impacts to a center in Houston affected by Harvey and the impacts of moving resources out of the affected location.

**Comment by sntdevco** [comment]
It still isn't available. Please try getting it fixed @czhower

**Comment by fanoI** [comment]
Well they hosting provider is literally in an Hurricane I think they have more urgent things to do now :-)

**Comment by Arawn-Davies** [comment]
Website back up - closed
