### ISSUE TITLE
Graphics not working

### ISSUE THREAD

**Issue by Gizego** [CosmosOS/Cosmos#801]
#### Area of Cosmos - What area of Cosmos are we dealing with?
Graphics

#### Expected Behaviour - What do you think that should happen?
Draw a few things

#### Actual Behaviour - What unexpectedly happens?
The system reads line instead of resizing canvas

#### Reproduction - How did you get this error to appear?
I just copy pasted the code in the graphics page

#### Version - Were you using the User Kit or Dev Kit? And what User Kit version or Dev Kit commit?
User Kit 2017

**Comment by Arawn-Davies** [comment]
Did you copy and paste the code from the GitHub wiki? That code is old and outdated, please see the documentation on http://www.gocosmos.org/docs/cosmos-graphic-subsystem/

**Comment by fanoI** [comment]
CGS - Cosmos Graphic Subsystem works only with Bochs, VirtualBox and QEMU currently.

**Comment by SapphireGitHub** [comment]
Well, if Arawn is right, you will have to go to CGS, not VGA. Personally, I am not a fan of CGS, because VGA was more advanced in features. It is possible to go back to VGA, but it is really advanced to switch and I have never done it before. (I tried once, but gave up.) jp2masa might tell you how to switch. And also, somebody tell me if I am wrong, I don't think you can create graphics with the User Kit at all... :( Try sending a snapshot.

**Comment by zarlo** [comment]
you can use graphics with the User Kit. CGS is built on top of the graphics driver (VGA/VBE).

**Comment by fanoI** [comment]
VGA gave you only DrawPoint() and max 640x480@16 colors... CGS will permit you to draw a lot of shapes and to select until 1920x1080@milion of colors! So it is really that is more advanced :-)
