### ISSUE TITLE
Improve compilation speed

### ISSUE THREAD

**Issue by mterwoord** [CosmosOS/Cosmos#9]

**Comment by kant2002** [comment]
Would like to take a look at this. From where I could started?
Speed of compilation for the whole solution shold be improved, or speed of XSharp compilation? Or maybe something else?

**Comment by mterwoord** [comment]
We're not sure what the fast or slow aspects are, but X# is just a fraction of what is being compiled.
Please look around a bit, and discuss before spending hours (or more) on changes....
There are a number of stages in full compilation: (Duration times are on my PC)
In MSBuild:
1. IL2CPU execution (takes 7-8 seconds)
2. Nasm execution (nasm.exe, not much speeding up here, 9-10 secs)
3. Relinking (ld executinh. Only used in ELF compilation)
4. objdump execution (also .exe running, not much to speed up Only used in ELF compilation)
5. Read symbols (from objdump) into cdb (takes 9-10 seconds Only used in ELF compilation)
6. Read symbols from nasm map (also takes 9-10 seconds, only used in binary compilation)

We'd really can only speedup step 1, 5 and 6. Other steps needing speedup are in the debugger, but that's a different issue...

**Comment by czhower** [comment]
On 1/14/2015 2:33 PM, Matthijs ter Woord wrote:
> We're not sure what the fast or slow aspects are, but X# is just a
> fraction of what is being compiled.

X# isn't the issue and it would be a waste to even look there as well as 
possibly complicating code that I really don't want complicated.

X# code as Matthijs said is tiny. The problem is somewhere in the IL to 
bin line.

> 1. IL2CPU execution (takes 7-8 seconds)
> 2. Nasm execution (nasm.exe, not much speeding up here, 9-10 secs)

Possible caching if we split the output, but that is complex.

> 3. Relinking (ld executinh. Only used in ELF compilation)
> 4. objdump execution (also .exe running, not much to speed up Only used
> in ELF compilation)

> 5. Read symbols (from objdump) into cdb (takes 9-10 seconds Only used in
> ELF compilation)
> 6. Read symbols from nasm map (also takes 9-10 seconds, only used in
> binary compilation)

This area is the easiest to speed up.

**Comment by kant2002** [comment]
1. IL2CPU execution - 
Most of the time spend in the 
Cosmos.Debug.Common.DebugInfo class 
Guid_NewGuid method
According to profiler 16% of time spent here.
Since Guid.NewGuid is already replaced with ulong, then probably we should go extra mile and replace Guids with ulong.
Time spent in that method is ~20% inclusive

item 5 and 6 is split second on the test applications.

So I think that refactoring is the only option.
Am I missing something?

**Comment by czhower** [comment]
On 1/15/2015 9:29 AM, Andrey Kurdyumov wrote:
>  1. IL2CPU execution - Most of the time spend in the
>     Cosmos.Debug.Common.DebugInfo class Guid_NewGuid method According to
>     profiler 16% of time spent here. Since Guid.NewGuid is already
>     replaced with ulong, then probably we should go extra mile and
>     replace Guids with ulong. Time spent in that method is ~20% inclusive

Yes GUID generation is very slow and we did some replacements already. 
Matthijs?

**Comment by mterwoord** [comment]
Well, I'm fine with replacing with long, as it basically is that already. Only issue is generating them. We have 2-4 processes generating them:
- IL2CPU
- Extract map steps
- debug engine when starting
- missing one?

we just need to make sure that works ok..

**Comment by kant2002** [comment]
Elf2Map extraction step could not be improved since 80% of it is the saving data to the database. SQLite is bottleneck.
