### ISSUE TITLE
No Cosmos Operating System template in VS 2017

### ISSUE THREAD

**Issue by V-Volte** [CosmosOS/Cosmos#954]
#### Expected Behaviour
A Cosmos solution containing two projects: Cosmos Kernel and Cosmos Boot.

#### Actual Behaviour
Only Cosmos Kernel is created, no Cosmos boot project.

#### Reproduction 
By Installing Devkit

#### Version
Devkit, Commit: ccb8fae

I had devkit on my old laptop for VS 2015 Professional and it worked perfectly. But this time, there is only one Cosmos template: Create Cosmos Kernel, and when I try to debug without altering any code, it says there were build errors.
![cosmoskernel4 - microsoft visual studio 4_15_2018 1_39_58 pm](https://user-images.githubusercontent.com/32711469/38776385-345026e0-40b3-11e8-825d-d6ad345f794e.png)

Error: System.ArgumentException: The Path is not of legal form

I have already reinstalled Cosmos, but the issue still persists.

**Comment by fanoI** [comment]
Maybe you have accented letters in your VS project path?

**Comment by Arawn-Davies** [comment]
I don't think the current project system has/uses Cosmos boot projects anymore, only the kernel project.
If you're wanting to split projects up into rings (albeit without the ring attributes), then what I did was remove the kernel overrides and inheritance from the new projects Kernel.cs, and remove the Cosmos.Build NuGet package, then referencing the new project in the old one.

Also, I don't think there can be spaces in the project path, which is another bug that ought to be fixed.

However, this did work until a couple of commits ago, when isolated assembly referencing was implemented. Not sure what happened exactly because I updated the old projects to include the 'cosmos' runtime identifier, but it's still not working :/
I'm going to open a new issue to explain exactly what's going on, bit of a bigger problem to say here.

**Comment by Arawn-Davies** [comment]
#957 is the issue, might be related, might not be so I've opened a separate one

**Comment by V-Volte** [comment]
@Arawn-Davies I created a new project in another place. The path now doesn't contain any spaces. But when I open the file, it says 'The type or namespace 'System' couldn't be found'. It does this for every single keyword in the project. I tried to add a reference, but there were none to choose.

I'm starting to think maybe getting VS 2015 with the old build is a better option.

**Comment by zarlo** [comment]
@V-Volte in the devkit the boot project was removed

**Comment by NanhuGITHUB** [comment]
Re-Add The Boot Project

**Comment by jp2masa** [comment]
Why do you want the Boot project? Is there any feature missing in the new project system?

**Comment by NanhuGITHUB** [comment]
The Boot Project (Obviously) Boots up The OS.

**Comment by db-noop** [comment]
No, you can just press Run

**Comment by NanhuGITHUB** [comment]
Oh. Maybe VMWare Player Missing?

**Comment by db-noop** [comment]
what do you mean?

**Comment by NanhuGITHUB** [comment]
VMWare Player might Not Be Installed.

**Comment by NanhuGITHUB** [comment]
See You Tomorrow. It's Late in my Location

**Comment by db-noop** [comment]
please make a separate issue

**Comment by NanhuGITHUB** [comment]
OK

**Comment by NanhuGITHUB** [comment]
"Nope, it just reverted back to 'The Path is not of legal form' error after I reinstalled COSMOS, even if there are no spaces in the new path."

Umm, Change the Path Back

**Comment by V-Volte** [comment]
After doing everything I could, the compiler now returns only one error: Project couldn't be booted or something like that.

**Comment by NanhuGITHUB** [comment]
Try Updating Your Cosmos Devkit Version Because There has been Many Commits after commit ccb8fae.

**Comment by V-Volte** [comment]
Funny how this is, but all this happens only on my new machine but works perfectly fine on my old one.
